@startuml

' Canvas Parameters
skinparam Linetype ortho
skinparam Nodesep 100
skinparam Ranksep 100
skinparam legendBackgroundColor #white

legend bottom right
    = Legende
    |<#LightGray>      | Abgeleitet aus FHIR-Kernspezifikation |
    |<#LightGreen>     | MII KDS-Modul |
    |<#LightYellow>    | Erweiterung |
endlegend

' MII KDS-Modul Person
package Person #LightGreen {
    class "Patient:in" <<Patient>> #LightGreen
    class "Patient:in - Pseudonymisiert" <<Patient>> #LightGreen
}

' MII KDS-Modul Fall
package Fall #LightGreen {
  class Einrichtungskontakt <<Encounter>> #LightGreen
  class Abteilungskontakt <<Encounter>> #LightGreen
  class Versorgungsstellenkontakt <<Encounter>> #LightGreen
}

' Klassen
class Dokument <<DocumentReference>> {
'   + {field} Masteridentifikator: Identifier <back:#yellow>[0..1 / ISiK: 1..1]</back>
    + {field} Masteridentifikator: Identifier [0..1]
    + {field} Businessidentifikator: Identifier [0..1]
    + {field} Dokumentenreferenzstatus: code [1..1]
    + {field} Dokumentenstatus: code [0..1]
'   + {field} Dokumententyp: CodeableConcept <back:#yellow>[0..1 / ISiK: 1..1]</back>
    + {field} Dokumententyp: CodeableConcept [0..1]
'   + {field} Dokumentenkategorie: CodeableConcept <back:#yellow>[0..* / ISiK: 0..1]</back>
    + {field} Dokumentenkategorie: CodeableConcept [0..*]
'   + {field} Patient: Reference(Patient) <back:#yellow>[0..1 / ISiK: 1..1]</back>
    + {field} Patient: Reference(Patient) [0..1]
'   + {field} Beschreibung: string <back:#yellow>[0..1 / ISiK: 1..1]</back>
    + {field} Beschreibung: string [0..1]
'   + {field} Sicherheitsstufe: CodeableConcept <back:#yellow>[0..* / ISiK: 1..*]</back>
    + {field} Sicherheitsstufe: CodeableConcept [0..*]
    + {field} Dokumentenbeziehung: BackboneElement [0..*]
'   + {field} Inhalt: BackboneElement <back:#yellow>[1..* / ISiK: 1..1]</back>
    + {field} Inhalt: BackboneElement [1..*]
'   + {field} Kontext: BackboneElement <back:#yellow>[0..1 / ISiK: 1..1]</back>
    + {field} Kontext: BackboneElement [0..1]
}

class Dokumentenbeziehung <<DocumentReference.relatesTo>> {
    + {field} Beziehungstyp: code [1..1]
    + {field} Beziehungsreferenz: Reference(DocumentReference) [1..1]
}

class Kontext <<DocumentReference.context>> {
'   + {field} Gesundheitseinrichtungskontakt: Reference(Encounter) <back:#yellow>[0..* / ISiK: 0..1]</back>
    + {field} Gesundheitseinrichtungskontakt: Reference(Encounter) [0..*]
    + {field} Vorgang: CodeableConcept [0..*]
    + {field} Dokumentationszeitraum: Period [0..1]
'   + {field} Einrichtungsart: CodeableConcept <back:#yellow>[0..1 / ISiK: 1..1]</back>
    + {field} Einrichtungsart: CodeableConcept [0..1]
'   + {field} Fachgebiet: CodeableConcept <back:#yellow>[0..1 / ISiK: 1..1]</back>
    + {field} Fachgebiet: CodeableConcept [0..1]
}

class Inhalt <<DocumentReference.content>> {
    + {field} Anhang: Attachment [1..1]
'   + {field} Dokumentenformat: Coding <back:#yellow>[0..1 / ISiK: 1..1]</back>
    + {field} Dokumentenformat: Coding [0..1]
}

class Anhang <<Attachment>> {
'   + {field} <back:#yellow>ISiK: MimeTyp: code [1..1]</back>
    + {field} Daten: base64Binary [0..1]
    + {field} DokumentenUrl: url [0..1]
'   + {field} Sprache: code <back:#yellow>[0..1 / ISiK: 1..1]</back>
    + {field} Sprache: code [0..1]
'   + {field} <back:#yellow>ISiK: Erstellungsdatum: dateTime [1..1]</back>
    + {field} Erstellungsdatum: dateTime [0..1]
}

' Beziehungen
Dokument *- "1..*" Inhalt: content >
Dokument *-l- "0..1" Kontext: context >
Dokument *-- "0..*" Dokumentenbeziehung: relatesTo >
Dokument o-u- "0..1" Person: subject >
Dokumentenbeziehung -- Dokument: target >
Inhalt -d- Anhang: attachment >
Kontext o-d- "0..*" Fall: encounter >
Einrichtungskontakt -- "0..*" Abteilungskontakt
Abteilungskontakt -- "0..*" Versorgungsstellenkontakt

@enduml